# RPM package for rh.short_file_to_float_file
# This file is regularly AUTO-GENERATED by the IDE. DO NOT MODIFY.

# By default, the RPM will install to the standard REDHAWK SDR root location (/var/redhawk/sdr)
# You can override this at install time using --prefix /new/sdr/root when invoking rpm (preferred method, if you must)
%{!?_sdrroot: %define _sdrroot /var/redhawk/sdr}
%define _prefix %{_sdrroot}
Prefix: %{_prefix}

Name: rh.short_file_to_float_file
Summary: Waveform rh.short_file_to_float_file
Version: 1.0.0
Release: 1%{?dist}
License: LGPLv3+
Group: REDHAWK/Waveforms
Source: %{name}-%{version}.tar.gz
# Require the controller whose SPD is referenced
Requires: rh.FileReader
# Require each referenced component
Requires: rh.FileReader rh.DataConverter rh.FileWriter
BuildArch: noarch
BuildRoot: %{_tmppath}/%{name}-%{version}

%description

%prep
%setup

%install
%__rm -rf $RPM_BUILD_ROOT
%__mkdir_p "$RPM_BUILD_ROOT%{_prefix}/dom/waveforms/rh/short_file_to_float_file"
%__install -m 644 short_file_to_float_file.sad.xml $RPM_BUILD_ROOT%{_prefix}/dom/waveforms/rh/short_file_to_float_file/short_file_to_float_file.sad.xml

%files
%defattr(-,redhawk,redhawk)
%dir %{_prefix}/dom/waveforms/rh/short_file_to_float_file
%{_prefix}/dom/waveforms/rh/short_file_to_float_file/short_file_to_float_file.sad.xml
